import time
from MotorController import MotorController

def testingMotors():
    motorController = MotorController()
    motorController.setupMotors()
    motorController.forward(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.backward(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.left(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.right(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.diagonalForwardLeft(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.diagonalBackwardRight(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.diagonalForwardRight(speed=0.8)
    time.sleep(2)
    motorController.stop()
    time.sleep(1)
    motorController.diagonalBackwardLeft(speed=0.8)
    time.sleep(2)
    motorController.stop()

if __name__ == '__main__':
    print("------------- Testeando Motores -------------")
    testingMotors()
    print("Programa finalizado...")